//
// openjpeg.h header binding for the Free Pascal Compiler aka FPC
//
// Binaries and demos available at http://www.djmaster.com/
//

(* create opj_config.h for CMake *)
const
  OPJ_HAVE_STDINT_H = 1;

(*--------------------------------------------------------------------------*)
(* OpenJPEG Versioning                                                      *)

(* Version number. *)
const
  OPJ_VERSION_MAJOR = 2;
  OPJ_VERSION_MINOR = 2;
  OPJ_VERSION_BUILD = 0;
